Jitting Chamfer 3D
Global seed set to 42
Loaded JIT 3D CUDA chamfer distance
dataset:  surreal
Traceback (most recent call last):
  File "/home/du2/22CS30065/SE-ORNet/train.py", line 109, in <module>
    main_train(model_class_pointer, hparams, parser)
  File "/home/du2/22CS30065/SE-ORNet/train.py", line 23, in main_train
    hparams = load_params_from_checkpoint(hparams, parser)
  File "/home/du2/22CS30065/SE-ORNet/utils/pytorch_lightning_utils.py", line 9, in load_params_from_checkpoint
    ckpt_dict = torch.load(path,map_location=torch.device('cpu'),weights_only=False)
  File "/home/du2/22CS30065/miniconda3/envs/se_ornet/lib/python3.10/site-packages/torch/serialization.py", line 1484, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/du2/22CS30065/miniconda3/envs/se_ornet/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/du2/22CS30065/miniconda3/envs/se_ornet/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output/shape_corr/PointCorrWithAngle/arch_PointCorrWithAngle/dataset_name_surreal/latent_dim_768/05_09:09:33:23/epoch-49.ckpt'
